on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: shadireg.azurecr.io
        username: ${{ secrets.acr_shadireg_username }}
        password: ${{ secrets.acr_shadireg_password }}
        
    - name: .Net Build
      # You may pin to the exact commit or the version.
      # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
      uses: EasyDesk/action-dotnet-build@v1.0.0
      
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t shadireg.azurecr.io/shcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push shadireg.azurecr.io/shcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_shcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sh-clusteracb3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sh-clusteracb3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sh-clusteracb3
        container-registry-url: shadireg.azurecr.io
        container-registry-username: ${{ secrets.acr_shadireg_username }}
        container-registry-password: ${{ secrets.acr_shadireg_password }}
        secret-name: shclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: sh-clusteracb3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          shadireg.azurecr.io/shcluster:${{ github.sha }}
        imagepullsecrets: |
          shclusterdockerauth
